AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Resources:
  OrdersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: ordersService
      CodeUri: ../../
      Handler: dist/out-tsc/services/orders/functions/index.lambdaHandler
      Runtime: nodejs14.x
      Events:
        GoToStep2:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /orders/client/go-to-step2
            Method: post 
        GoToStep3:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /orders/client/go-to-step3
            Method: post 
            

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OrdersApi:
    Description: "API Gateway endpoint URL for Prod stage for Orders"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders/"
  OrdersFunction:
    Description: "Orders Function ARN"
    Value: !GetAtt OrdersFunction.Arn
  OrdersIamRole:
    Description: "Implicit IAM Role created for Orders function"
    Value: !GetAtt OrdersFunctionRole.Arn
