AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Orders Service


Parameters: 
  env:
    Type: String
    Default: "dev"
    AllowedValues:
      - dev
      - test
      - prod
    Description: Envrionment value. Enter dev, test or prod. Default is dev.
  AuthFunctionArn:
    Type: String
    Default: 'some-arn'
    Description: Specify ARN for AuthFunction
  AuthFunctionInvokeRoleArn:
    Type: String
    Default: 'some-arn'
    Description: Specify ARN for AuthFunctionInvokeRole

Resources:
  OrdersApi:
      Type: AWS::Serverless::HttpApi
      Properties:
        StageName: !Ref env
        DefinitionUri: ./api-def.yaml
  OrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ordersService
      CodeUri: ../../dist/out-tsc/
      Handler: services/orders/functions/index.lambdaHandler
      Runtime: nodejs14.x
      Events:
        GoToStep2:
          Type: HttpApi
          Properties:
            ApiId: !Ref OrdersApi
            Path: /orders/client/go-to-step2
            Method: post
            Auth:
              Authorizer: LambdaAuthorizer
        GoToStep3:
          Type: HttpApi
          Properties:
            ApiId: !Ref OrdersApi
            Path: /orders/client/go-to-step3
            Method: post 
            Auth:
              Authorizer: LambdaAuthorizer
  # PlaceOrdersStateMachine:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./workflows/place-order/template.yaml
  #     Parameters:
  #       env: !Ref env
  #       OrdersFunctionArn: !GetAtt OrdersFunction.Arn
  #       PaymentsFunctionArn: !GetAtt OrdersFunction.Arn
  #       NotificationsFunctionArn: !GetAtt OrdersFunction.Arn
  #       OrdersApiId: !Ref OrdersApi
            
Outputs:
  OrdersApiUrl:
    Description: URL of your OrdersApi endpoint
    Value:
      Fn::Sub: 'https://${OrdersApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${env}/'
  OrdersApiId:
    Description: Api id of OrdersApi
    Value:
      Ref: OrdersApi
  OrdersFunction:
    Description: "Orders Function ARN"
    Value: !GetAtt OrdersFunction.Arn
  OrdersIamRole:
    Description: "Implicit IAM Role created for Orders function"
    Value: !GetAtt OrdersFunctionRole.Arn
