version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:sts::812042964529:assumed-role/AWSReservedSSO_PCFF-DEV-ADMIN_ddeee641120a0820/imaanvir.brar@gov.ab.ca"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::812042964529:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-XRX9SFC72IP7"
cloudformation_execution_role = "arn:aws:iam::812042964529:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-F4DVVPL3YBXN"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-jm2ie85jtwor"
image_repository = ""
region = "ca-central-1"

[uat]
[uat.pipeline_bootstrap]
[uat.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::812042964529:role/aws-sam-cli-managed-uat-pipe-PipelineExecutionRole-KXTTTYXQMIF"
cloudformation_execution_role = "arn:aws:iam::812042964529:role/aws-sam-cli-managed-uat-p-CloudFormationExecutionR-1EWZLOSJ99LR4"
artifacts_bucket = "aws-sam-cli-managed-uat-pipeline-artifactsbucket-ui767vydxwdi"
image_repository = ""
region = "ca-central-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::812042964529:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-2YN6F6WSDFPJ"
cloudformation_execution_role = "arn:aws:iam::812042964529:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-PG8D6TH1Y61K"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1gzcns30go8le"
image_repository = ""
region = "ca-central-1"
